# -*- coding: utf-8 -*-
"""BestNYCSchools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7RHwswDQdq-bfUbXCyfpMztkzX9e39w
"""

import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

schools.info()

# Create Pandas DataFrame
df = pd.DataFrame(schools)

# Schools with the best math results
best_math_schools = df[df['average_math'] >= 0.8 * 800][['school_name', 'average_math']].sort_values(by='average_math', ascending=False)
print("Best Math Schools:\n", best_math_schools)

# Top 10 performing schools based on combined SAT scores
df['total_SAT'] = df[['average_math', 'average_reading', 'average_writing']].sum(axis=1)
top_10_schools = df[['school_name', 'total_SAT']].sort_values(by='total_SAT', ascending=False).head(10)
print("Top 10 Schools:\n", top_10_schools)

# Borough with the largest standard deviation in combined SAT scores
borough_stats = df.groupby('borough')['total_SAT'].agg(['mean', 'std', 'count']).reset_index()
print(borough_stats)
largest_std_dev = borough_stats.loc[borough_stats['std'].idxmax()][['borough', 'count', 'mean', 'std']]
largest_std_dev = pd.DataFrame([largest_std_dev])
largest_std_dev.columns = ['borough', 'num_schools', 'average_SAT', 'std_SAT']
largest_std_dev = largest_std_dev.round(2)
print("\nBorough with Largest Std Dev:\n", largest_std_dev)